version: "3.2"

services:
  web:
    build: .
    command: nodemon.cmd --inspect=0.0.0.0:9229 app.js
    working_dir: C:\code
    volumes:
      # - .:c:\code
      - type: bind
        source: C:\Users\stefan\code\dockerfiles-windows\node-example
        target: C:\code

    ports:
      - "8000:8000"
      - "9229:9229"

networks:
  default:
    external:
      name: nat
